### ISSUE TITLE
Docker image: 404 when requesting data

### ISSUE THREAD

**Issue by scribu** [Parallels/rq-dashboard#162]
If I build the Docker image and run it, the dashboard loads fine, but it doesn't load any data.

Using this minimal docker-compose.yml file:

```yaml
version: '3'

volumes:
  redis-data:

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/var/lib/redis
    restart: always
    ports:
      - "6380:6379"

  dashboard:
    build: .
    ports:
      - "8080:80"

    depends_on:
      - redis
```

... you can see that all the data endpoints return 404s for some reason:

```
$ docker-compose up
...
dashboard_1  | RQ Dashboard version 0.3.12
dashboard_1  |  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:51] "GET / HTTP/1.1" 200 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:52] "GET /rq-instances.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:52] "GET /queues.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:52] "GET /workers.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:52] "GET /jobs/default/1.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:54] "GET /queues.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:54] "GET /workers.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:54] "GET /jobs/default/1.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:57] "GET /queues.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:57] "GET /workers.json HTTP/1.1" 404 -
dashboard_1  | 172.18.0.1 - - [28/Aug/2018 15:59:57] "GET /jobs/default/1.json HTTP/1.1" 404 -
```
